import type { SearchVerticalConfig } from '../verticals';

export const PRICING_VERTICAL: SearchVerticalConfig = {
  id: 'pricing',
  label: 'Pricing',
  description:
    'Focused vertical for extracting provider pricing, self-pay fees, and related financial details from provider websites and documents.',
  defaultOperators: ['filetype:pdf'],
  queryExpansions: [
    'cash price',
    'self pay',
    'fee schedule',
    'price list',
    'pricing',
    'occupational health pricing',
    'DOT physical price',
    'drug screen price',
    'audiogram price',
    'spirometry price',
    'pulmonary function test price',
    'fit test price',
    'filetype:pdf',
  ],
  includedDomains: [],
  excludedDomains: [],
  preferredFileTypes: ['pdf'],
  extractionTargets: [
    'provider_name',
    'service_name',
    'price',
    'currency',
    'address',
    'phone',
    'email',
    'evidence_text',
    'source_url',
    'confidence',
  ],
  rankingBoosts: {
    govDomain: 50,
    usDomain: 30,
    pdf: 40,
    exactPhrase: 15,
    containsPricing: 25,
    containsEmail: 10,
    containsDueDate: 5,
    occupationalHealthTerms: 20,
  },
  feedbackLabels: [
    'contains_price',
    'no_price_found',
    'wrong_source',
    'stale',
    'duplicate',
    'good_result',
    'bad_result',
  ],
};
